version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/moul.io/depviz
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make install
      - run: make test
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.2
      - run: PATH="$PATH:$(pwd)/bin" make lint
